# Generated by Django 5.0.1 on 2024-03-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollment_duedate_enrollment_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='Phonenumer',
            new_name='Phonenumber1',
        ),
    ]
