# Generated by Django 5.0.1 on 2024-03-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_phonenumer_enrollment_phonenumber1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='Phonenumber1',
            new_name='Phonenumber',
        ),
    ]
