# Generated by Django 5.0.1 on 2024-03-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_attendance_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainerimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='trainers')),
            ],
        ),
    ]
